### ISSUE TITLE
(September 9-10) GDG DevFest Ukraine 2016 - https://devfest.gdg.org.ua/

### ISSUE THREAD

**Issue by sophieH29** [tstringer/awesome-tech-conferences#48]
(September 9-10) GDG DevFest Ukraine 2016 - the biggest Google tech conference in Ukraine, all about Android, Web & Cloud  from the world experts https://devfest.gdg.org.ua/

**Comment by trstringer** [comment]
Added 😄

**Comment by sophieH29** [comment]
thanks and sorry for doubled issue :)

**Comment by trstringer** [comment]
:smile: No problem on that, around the time you were creating the issues it looks like GitHub was having a few issues, so I just blamed it on that :smile:

And thank _you_ for the contribution! 👍
