### ISSUE TITLE
GDG DevFest Ukraine 2016 - https://devfest.gdg.org.ua/

### ISSUE THREAD

**Issue by sophieH29** [tstringer/awesome-tech-conferences#49]
:star: (September 9-10)  [GDG DevFest Ukraine 2016](https://devfest.gdg.org.ua/) (Ukraine, Lviv) - the biggest Google tech conference in Ukraine, all about Android, Web and Cloud from the world experts!

**Comment by trstringer** [comment]
@sophieH29 I've added this to the list, thanks! 👍 😄
